# THIS IS A SAMPLE PYTHON SCRIPT.

# PRESS SHIFT+F10 TO EXECUTE IT OR REPLACE IT WITH YOUR CODE.
# PRESS DOUBLE SHIFT TO SEARCH EVERYWHERE FOR CLASSES, FILES, TOOL WINDOWS, ACTIONS, AND SETTINGS.


DEF PRINT_HI(NAME):
    # USE A BREAKPOINT IN THE CODE LINE BELOW TO DEBUG YOUR SCRIPT.
    PRINT(F'HI, {NAME}')  # PRESS CTRL+F8 TO TOGGLE THE BREAKPOINT.


# PRESS THE GREEN BUTTON IN THE GUTTER TO RUN THE SCRIPT.
IF __NAME__ == '__MAIN__':
    PRINT_HI('PYCHARM')

# SEE PYCHARM HELP AT HTTPS://WWW.JETBRAINS.COM/HELP/PYCHARM/
